baseURL = 'https://bledley.xyz/'
languageCode = 'en-us'
title = 'ğŸŒ€ bledleys blog'
theme = 'rocinante'
pagination_pagerSize = 6
customCSS = ["css/custom_style.css"]

[Author]
name = "Bledley"
email = "bledley@posteo.com"

[markup]
[markup.highlight]
style = "monokailight"
[markup.goldmark.renderer]
unsafe = true

[params]
mainSections = ["posts"]
email = "bledley@posteo.com"
favicon = "icons/favicon.jpg"

# about = """
# what of it..
# """

# google_fonts = ["//fonts.googleapis.com/css?family=JetBrains+Mono"]
# body_font = "JetBrains+Mono"

# google_fonts = ["//fonts.googleapis.com/css?family=Fira+Sans"]
# body_font = "Fira+Sans"

google_fonts = ["//fonts.googleapis.com/css?family=IBM+Plex+Serif"]
body_font = "IBM+Plex+Serif"

[[params.links]]

[[params.links.link]]
name = "ğŸ  Home"
href = "https://bledley.xyz/"

[[params.links.link]]
  name = "ğŸ–¼ Gallery"
  href = "https://portfolio.pixelfed.social/bledley"
  new_tab = true

[[params.links.link]]
name = "âœ‰ Message"
href = "/contact"
smart_email_link = true

[[params.links.link]]
name = "â†ª Follow"
href = "/socials"

[[params.links.link]]
name = "â˜• Thanks"
href = "/kofi"

# [[params.links.link]]
#   name = "Youtube"
#   href = "https://www.youtube.com/@bledleysworldv/"
#   new_tab = true

# [[params.links.link]]
#   name = "Navigators"
#   href = "/navigators"
#   new_tab = true

#[[params.links.link]]
# name = "RSS"
# href = "/index.xml"
# new_tab = true

[[params.links.link]]
name = "ğŸ’­ Stuff"
href = "/links"
