title = 'bledley's blog'
theme = 'rocinante'
baseURL = 'https://itsbledley.netlify.app/'
languageCode = 'en-us'

pagination_pagerSize = 6

customCSS = ["css/custom_style.css"]

[Author]
name = "Bledley"
email = "itsbledley@posteo.com"

[markup]
[markup.highlight]
style = "monokaidark"
[markup.goldmark.renderer]
unsafe = true

[params]
mainSections = ["posts"]
email = "itsbledley@posteo.com"
favicon = "icons/favicon.jpg"

# about = """
# what of it..
# """

google_fonts = ["//fonts.googleapis.com/css?family=JetBrains+Mono"]
body_font = "JetBrains+Mono"

[[params.links]]

[[params.links.link]]
name = "ğŸ  Home"
href = "https://itsbledley.netlify.app/"

[[params.links.link]]
name = "ğŸ’¬ Message"
href = "/contact"
smart_email_link = true

[[params.links.link]]
name = "â†ªï¸ Follow"
href = "/socials"

[[params.links.link]]
name = "â˜• Thanks"
href = "/kofi"

# [[params.links.link]]
#   name = "Youtube"
#   href = "https://www.youtube.com/@itsbledley_tv/"
#   new_tab = true

# [[params.links.link]]
#   name = "Instagram"
#   href = "https://instagram.com/itsbledley/"
#   new_tab = true

# [[params.links.link]]
#   name = "Navigators"
#   href = "/navigators"
#   new_tab = true

#[[params.links.link]]
# name = "RSS"
# href = "/index.xml"
# new_tab = true

[[params.links.link]]
name = "ğŸ’­ Stuff"
href = "/links"
